# GitHub Actions workflow to lint Python code using 'ruff' on a Windows runner

name: Python Linter on Windows

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job is named "lint"
  lint:
    # The type of runner that the job will run on - CORRECTED FOR WINDOWS
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up a specific version of Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install project dependencies and the linter
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          pip install -r requirements.txt

      # Step 4: Run the ruff linter on all Python files
      - name: Run ruff linter
        run: |
          ruff check . --output-format=github
